### ISSUE TITLE
ZE API: cannot append properties to a custom profile with user-specific config file

### ISSUE THREAD

**Issue by roman-kupriyanov** [zowe/vscode-extension-for-zowe#1895]
**Describe the bug**

I have created an additional `zowe.config.user.json` file to accompany my `zowe.config.json` with existing profiles (see examples in the **Additional context section**). The idea is to append some user specific fields to the existing profile from global team config using the user-specific config.

But on the initialization of Zowe Explorer API I keep getting the error:

```
'ProfInfoErr: Failed to find property rejectUnauthorized in the profile base_def'
```
(to be precise: during the profiles reloading `ZoweVsCodeExtension.getZoweExplorerApi().getExplorerExtenderApi().reloadProfiles()`)

In the same time Zowe CLI seems to work good with this setup.

The only workaround I found so far is to duplicate the `base_def`profile in the user-specific config, in this case it is possible to pass the profiles reloading and to use the merged profile successfully.

**Expected behavior**

ZE API should allow to retrieve the profiles merged from global and user configs.

**Desktop (please complete the following information):**

- OS: **MacOS**
- Zowe Explorer Version: **2.2.0**
- (Optional) Zowe CLI Version: **7.4.0**
- (Optional) Are you using Secure Credential Store? **Yes**

**Additional context**

We have a `zowe.config.json` with some custom profiles:

```json
{
    "$schema": "./zowe.schema.json",
    "profiles": {
        "base_def": {
            "type": "base",
            "properties": {
                "rejectUnauthorized": false
            },
            "secure": [
                "user",
                "password"
            ]
        },
        "test": {
            "type": "endevor",
            "properties": {
                "host": "test.com",
                "port": 1234,
                "protocol": "http",
                "basePath": "/"
            },
            "secure": []
        },
        "test-location": {
            "type": "endevor-location",
            "properties": {
                "instance": "INST",
                "environment": "ENV",
                "system": "SYS",
                "subsystem": "SBS",
                "stageNumber": "1",
                "type": "*"
            },
            "secure": []
        },
        "test-zosmf": {
            "type": "zosmf",
            "properties": {
                "host": "1.2.3.4",
                "port": 43,
                "protocol": "https"
            },
            "secure": [
                "user",
                "password"
            ]
        },
    },
    "defaults": {
        "base": "base_def",
        "endevor": "test",
        "endevor-location": "test-location",
        "zosmf": "test-zosmf"
    },
    "autoStore": true
}
```

And a `zowe.config.user.json`:

```json
{
    "$schema": "./zowe.schema.json",
    "profiles": {
        "test-location": {
            "type": "endevor-location",
            "properties": {
                "ccid": "develop1",
                "comment": "Changes by develop1"
            },
            "secure": []
        }
    },
    "defaults": {},
    "autoStore": true
}
```

Both are in `.zowe` directory.

Zowe CLI output:
```yaml
❯ zowe config ls
profiles: 
  base_def: 
    type:       base
    properties: 
      rejectUnauthorized: false
      user:               (secure value)
      password:           (secure value)
    secure: 
      - user
      - password
  test: 
    type:       endevor
    properties: 
      host:     test.com
      port:     1234
      protocol: http
      basePath: /
    secure: 
      (empty array)
  test-location: 
    type:       endevor-location
    properties: 
      instance:    INST
      environment: ENV
      system:      SYS
      subsystem:   SBS
      stageNumber: 1
      type:        *
      ccid:        develop1
      comment:     Changes by develop1
    secure: 
      (empty array)
  test-zosmf: 
    type:       zosmf
    properties: 
      host:        1.2.3.4
      port:        43
      protocol:    https
    secure: 
      - user
      - password
defaults: 
  base:             base_def
  endevor:          test
  endevor-location: test-location
  zosmf:            test-zosmf
autoStore: true
```

**Comment by roman-kupriyanov** [comment]
Not sure if it would be somehow helpful in this case.. I have just checked it out that it works if team config and user config do not have the "base" type profile specified at all.

**Comment by zFernand0** [comment]
This sounds related to zowe/imperative#881

**Comment by roman-kupriyanov** [comment]
@zFernand0 Sure, I will recheck it and let you know, thanks!

**Comment by roman-kupriyanov** [comment]
Hi @zFernand0

Good news, I have tested the latest ZE v2.3.0 with our extension and team/user config setup, described above, and now it is initialized properly without errors, yay! Thank you for the help 😃 

I have noticed some kind of a related issue for ZE though. Now it does not respect a base profile specified in the User config on the global level (in `~/.zowe` folder), but it seems that it respects it on the project level (if an opened VSCode workspace folder includes Team and User configs). In the same time I tried the same setup with Zowe CLI v7.6.2 and it work fine with the global level User configs too.

I must say I do not know where exactly it is expected for User config to be located (probably, most of the time on the project level, not on the global one), but since Zowe CLI support both scenarios, I would expect ZE to do the same. And we actually have some customers who might be interested to specify their base profile in User config, not to be shareable  with anyone else.

Examples:

`~/.zowe/zowe.config.json` config:
  ```json
{
    "$schema": "./zowe.schema.json",
    "profiles": {
        "test": {
            "type": "endevor",
            "properties": {
                "host": "test.com",
                "port": 1234,
                "protocol": "http",
                "basePath": "/"
            },
            "secure": []
        },
        "test-location": {
            "type": "endevor-location",
            "properties": {
                "instance": "INST",
                "environment": "ENV",
                "system": "SYS",
                "subsystem": "SBS",
                "stageNumber": "1",
                "type": "*"
            },
            "secure": []
        },
        "test-zosmf": {
            "type": "zosmf",
            "properties": {
                "host": "1.2.3.4",
                "port": 43,
                "protocol": "https"
            },
            "secure": [
                "user",
                "password"
            ]
        },
    },
    "defaults": {
        "endevor": "test",
        "endevor-location": "test-location",
        "zosmf": "test-zosmf"
    },
    "autoStore": true
}
```

And `~/.zowe/zowe.config.user.json` config:
```json
{
    "$schema": "./zowe.schema.json",
    "profiles": {
        "base_def": {
            "type": "base",
            "properties": {
                "rejectUnauthorized": false
            },
            "secure": [
                "user",
                "password"
            ]
        },
        "test-location": {
            "type": "endevor-location",
            "properties": {
                "ccid": "develop1",
                "comment": "Changes by develop1"
            },
            "secure": []
        }
    },
    "defaults": {
        "base": "base_def"
    },
    "autoStore": true
}
```

Zowe CLI output:
```yaml
❯ zowe config ls
profiles: 
  test: 
    type:       endevor
    properties: 
      host:     test.com
      port:     1234
      protocol: http
      basePath: /
    secure: 
      (empty array)
  test-location: 
    type:       endevor-location
    properties: 
      instance:    INST
      environment: ENV
      system:      SYS
      subsystem:   SBS
      stageNumber: 1
      type:        *
      ccid:        develop1
      comment:     Changes by develop1
    secure: 
      (empty array)
  test-zosmf: 
    type:       zosmf
    properties: 
      host:        1.2.3.4
      port:        43
      protocol:    https
    secure: 
      - user
      - password
  base_def: 
    type:       base
    properties: 
      rejectUnauthorized: false
      user:               (secure value)
      password:           (secure value)
    secure: 
      - user
      - password
defaults: 
  base:             base_def
  endevor:          test
  endevor-location: test-location
  zosmf:            test-zosmf
autoStore: true
```

I have even tried this weird flow and it worked:
- Set the `zowe.config.json` and `zowe.config.user.json` configs in `~/.zowe` folder.
- Open any folder without configs in VSCode (or do not open at all): the extension have no information about credentials specified (the base profile is not merged it seems).
- Open `~/.zowe` folder in VSCode (with Open Folder dialog): and now it detects the base profile information.

Because of this scenario I have an assumption about that it works only with the project level configs and not global ones. But maybe something else is involved. In the same time Zowe CLI works in all cases, whether you are in the `~/.zowe` folder or in any else.
