### ISSUE TITLE
Clean-up rediscovered code smells; adjust ESLint rules + add plugin for SonarJS

### ISSUE THREAD

**Issue by traeok** [zowe/vscode-extension-for-zowe#2063]
**Is your feature request related to a problem? Please describe.**

After TSLint is removed from the codebase, SonarCloud reported code smells for some functions that were previously ignored. These code smells should be resolved separately from the TSLint/ESLint changes.

In addition, we should look over the new rules added and determine which ones should be marked as "warn" or "error" :

```yaml
  "@typescript-eslint/consistent-type-assertions": warn
  "@typescript-eslint/no-namespace": warn
  "@typescript-eslint/no-var-requires": warn
  no-unused-expressions: off
  "@typescript-eslint/no-unused-expressions": warn
  curly: warn
  max-len:
    - warn
    - code: 150
  no-console: warn
  no-duplicate-case: warn
  no-duplicate-imports: warn
  no-extra-bind: warn
  no-irregular-whitespace: warn
  no-magic-numbers:
    - warn
    - "ignore": [-1, 0, 1, 2, 4]
  no-multiple-empty-lines: warn
  no-return-await: warn
  no-sequences: warn
  no-sparse-arrays: warn
  prefer-object-spread: warn
  space-in-parens: warn
```

**Describe the solution you'd like**

Update the ESLint rules above with preferred modes (warning/error), and add the ESLint plugin for SonarJS to help catch code smells locally: https://github.com/SonarSource/eslint-plugin-sonarjs
